# Generated by Django 5.2.8 on 2025-11-14 22:29

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('read', models.BooleanField(default=False, verbose_name='Lu')),
                ('replied', models.BooleanField(default=False, verbose_name='Répondu')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Entreprise')),
                ('position', models.CharField(max_length=200, verbose_name='Poste')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('current', models.BooleanField(default=False, verbose_name='Poste actuel')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
                'ordering': ['-start_date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('tagline', models.CharField(max_length=300, verbose_name='Slogan/Tagline')),
                ('bio', ckeditor.fields.RichTextField(verbose_name='Biographie')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('location', models.CharField(max_length=200, verbose_name='Localisation')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('resume_file', models.FileField(blank=True, upload_to='resumes/', verbose_name='CV (PDF)')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/', verbose_name='Photo de profil')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('page', models.CharField(max_length=500, verbose_name='Page visitée')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Date/Heure')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('tools', 'Outils & Autres')], max_length=20, verbose_name='Catégorie')),
                ('proficiency', models.IntegerField(default=50, help_text='0-100', verbose_name='Niveau (%)')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône CSS')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description courte')),
                ('detailed_description', ckeditor.fields.RichTextField(verbose_name='Description détaillée')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Image principale')),
                ('github_url', models.URLField(blank=True, verbose_name='Lien GitHub')),
                ('demo_url', models.URLField(blank=True, verbose_name='Lien démo')),
                ('status', models.CharField(choices=[('completed', 'Terminé'), ('in_progress', 'En cours'), ('archived', 'Archivé')], default='completed', max_length=20, verbose_name='Statut')),
                ('featured', models.BooleanField(default=False, verbose_name='Projet mis en avant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('views', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('technologies', models.ManyToManyField(to='portfolio.skill', verbose_name='Technologies utilisées')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
                'ordering': ['-featured', 'order', '-created_at'],
            },
        ),
    ]
