# Generated by Django 5.2.8 on 2025-11-15 01:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True, verbose_name='Clé de session')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre')], default='light', max_length=10, verbose_name='Thème')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Préférence utilisateur',
                'verbose_name_plural': 'Préférences utilisateur',
            },
        ),
        migrations.AddField(
            model_name='experience',
            name='company_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Entreprise (EN)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieu (EN)'),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Poste (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description courte (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='detailed_description_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Description détaillée (EN)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titre (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bio_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Biographie (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='location_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Localisation (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='resume_file_en',
            field=models.FileField(blank=True, upload_to='resumes/', verbose_name='CV (PDF) - EN'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Slogan/Tagline (EN)'),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nom (EN)'),
        ),
    ]
