# Generated by Django 5.2.8 on 2025-11-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_userpreferences_experience_company_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPreferences',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='company_en',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='detailed_description_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='bio_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='resume_file_en',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='tagline_en',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='name_en',
        ),
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='contact',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='contact',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='contact',
            name='project_budget',
            field=models.CharField(blank=True, max_length=100, verbose_name='Budget estimé'),
        ),
        migrations.AddField(
            model_name='contact',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse'),
        ),
        migrations.AddField(
            model_name='contact',
            name='reply_message',
            field=models.TextField(blank=True, verbose_name='Message de réponse'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
    ]
