# Generated by Django 5.2.8 on 2025-11-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_delete_userpreferences_remove_experience_company_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='project_budget',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='replied_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='reply_message',
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la certification')),
                ('issuer', models.CharField(max_length=200, verbose_name='Organisme délivrant')),
                ('date_obtained', models.DateField(verbose_name="Date d'obtention")),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('credential_id', models.CharField(blank=True, max_length=100, verbose_name='ID de certification')),
                ('credential_url', models.URLField(blank=True, verbose_name='URL de vérification')),
                ('certificate_file', models.FileField(blank=True, help_text='Formats acceptés: PDF, JPG, PNG (max 5MB)', upload_to='certifications/', verbose_name='Fichier certificat (PDF/Image)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('featured', models.BooleanField(default=False, verbose_name='Certification mise en avant')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('skills_covered', models.ManyToManyField(blank=True, to='portfolio.skill', verbose_name='Compétences couvertes')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'ordering': ['-featured', 'order', '-date_obtained'],
            },
        ),
    ]
