# Generated by Django 5.2.8 on 2025-11-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_contact_company_remove_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='contact',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='contact',
            name='project_budget',
            field=models.CharField(blank=True, max_length=100, verbose_name='Budget estimé'),
        ),
        migrations.AddField(
            model_name='contact',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse'),
        ),
        migrations.AddField(
            model_name='contact',
            name='reply_message',
            field=models.TextField(blank=True, verbose_name='Message de réponse'),
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
    ]
