# Generated by Django 5.2.8 on 2025-11-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_contact_company_contact_phone_contact_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='twitter',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Numéro de téléphone au format international (ex: +33612345678)', max_length=20, verbose_name='WhatsApp'),
        ),
    ]
